### ISSUE TITLE
Forks of this repository are hard to test, since the repo URL is all over the place

### ISSUE THREAD

**Issue by eric-wieser** [cc-scripts/cc-scripts#13]
Would be better if the url could be restricted to the bootstrapper, so that it can easily be changed,

**Comment by damien** [comment]
I'll start reviewing these changes. One thing that caught my attention thought: tabs vs spaces. I've been using two column wide soft-tabs (spaces), as that's what I'm used to and the in game lua editor seems to handle it well.

Does Lua conventionally use tabs or spaces? I tried checking the [Lua Style Guide](http://lua-users.org/wiki/LuaStyleGuide), but it didn't really advocate one over the other.

**Comment by eric-wieser** [comment]
For some reason I'd thought that I'd seen files with tabs in, and the spaces were inconsistent. Having made the rest of the changes, I realize I was wrong. Feel free to skip that commit.

What does the in-game editor do to tabs?

**Comment by damien** [comment]
From what I've seen, the in game editor treats tabs as 4-column wide hard tabs. Hitting return will indent the following line with soft tabs (spaces).

**Comment by eric-wieser** [comment]
If we're trying to make things look good in the in-game editor, we'll also want to cap our columns to 39/51 chars... (or implement our own line-wrapping editor)
